project: default
source:
  repoURL: 'https://github.com/gratiangaga/argocd-example'
  path: argocd
  targetRevision: master
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
